### ISSUE TITLE
SQLite errors with Spigot 1.20.2

### ISSUE THREAD

**Issue by Black-Hole** [PaintballWarEdition/PaintballLegacy#3]
Spigot updated the SQLite driver with 1.20.2:
https://hub.spigotmc.org/jira/browse/SPIGOT-7491

So the Paintball plugin is throwing a lot of exceptions and won't work with 1.20.2:
[18:55:20] [Server thread/WARN]: java.sql.SQLFeatureNotSupportedException: not implemented by SQLite JDBC driver
[18:55:20] [Server thread/WARN]:        at org.sqlite.jdbc3.JDBC3Statement.unsupported(JDBC3Statement.java:419)
[18:55:20] [Server thread/WARN]:        at org.sqlite.jdbc3.JDBC3Statement.getGeneratedKeys(JDBC3Statement.java:357)
[18:55:20] [Server thread/WARN]:        at Paintball.jar//de.blablubbabc.BlaDB.BlaSQLite.updateQueryRaw(BlaSQLite.java:305)
[18:55:20] [Server thread/WARN]:        at Paintball.jar//de.blablubbabc.BlaDB.BlaSQLite.updateQuery(BlaSQLite.java:312)
[18:55:20] [Server thread/WARN]:        at Paintball.jar//de.blablubbabc.BlaDB.BlaSQLite.createDefaultTable(BlaSQLite.java:365)
[18:55:20] [Server thread/WARN]:        at Paintball.jar//de.blablubbabc.BlaDB.SQLArenaLobby.createDefaultTables(SQLArenaLobby.java:37)
[18:55:20] [Server thread/WARN]:        at Paintball.jar//de.blablubbabc.BlaDB.SQLArenaLobby.<init>(SQLArenaLobby.java:31)
[18:55:20] [Server thread/WARN]:        at Paintball.jar//de.blablubbabc.BlaDB.BlaSQLite.<init>(BlaSQLite.java:75)
[18:55:20] [Server thread/WARN]:        at Paintball.jar//de.blablubbabc.paintball.Paintball.onEnable(Paintball.java:1001)

Spigot might revert the SQLite driver update, but will update to newer SQLite versions in future updates. So sooner or later the database queries needs to be adapted to this change.

**Comment by blablubbabc** [comment]
This might no longer be an issue due to https://github.com/xerial/sqlite-jdbc/pull/1035
